(part "EFM8BB21F16A-C-QFN20"
    (packageRef "EFM8BB21F16ACQFN20")
    (interface
        (port "1" (symbPinId 1) (portName "P0.1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "P0.0") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RSTB_/_C2CK") (portType INOUT))
        (port "6" (symbPinId 6) (portName "P2.0_/_C2D") (portType INOUT))
        (port "7" (symbPinId 7) (portName "P1.6") (portType INOUT))
        (port "8" (symbPinId 8) (portName "P1.5") (portType INOUT))
        (port "9" (symbPinId 9) (portName "P1.4") (portType INOUT))
        (port "10" (symbPinId 10) (portName "P1.3") (portType INOUT))
        (port "11" (symbPinId 11) (portName "P1.2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GND_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "P1.1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "P1.0") (portType INOUT))
        (port "15" (symbPinId 15) (portName "P0.7") (portType INOUT))
        (port "16" (symbPinId 16) (portName "P0.6") (portType INOUT))
        (port "17" (symbPinId 17) (portName "P0.5") (portType INOUT))
        (port "18" (symbPinId 18) (portName "P0.4") (portType INOUT))
        (port "19" (symbPinId 19) (portName "P0.3") (portType INOUT))
        (port "20" (symbPinId 20) (portName "P0.2") (portType INOUT))
        (port "21" (symbPinId 21) (portName "GND_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Silicon Labs")
    (property "Manufacturer_Part_Number" "EFM8BB21F16A-C-QFN20")
    (property "Mouser_Part_Number" "634-EFM8BB21F16FN20")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Silicon-Labs/EFM8BB21F16A-C-QFN20?qs=8HqIXBaaO6yFJdjkDKkkeA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "IC MCU 8BIT 16KB FLASH 20QFN")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/EFM8BB21F16A-C-QFN20.pdf")
    (property "symbolName1" "EFM8BB21F16A-C-QFN20")
)
