(part "AP2127K-3_3TRG1"
    (packageRef "SOT95P282X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%SHUTDOWN%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC/ADJ") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AP2127K-3.3TRG1")
    (property "Mouser_Part_Number" "621-AP2127K-3.3TRG1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AP2127K-3.3TRG1?qs=x6A8l6qLYDCeAxisWuFs5g%3D%3D")
    (property "Arrow_Part_Number" "AP2127K-3.3TRG1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ap2127k-3.3trg1/diodes-incorporated?utm_currency=USD&region=nac")
    (property "Description" "DiodesZetex AP2127K-3.3TRG1, LDO Regulator, 3.3 V, +/-2% 5-Pin, SOT-23")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/AP2127.pdf")
    (property "symbolName1" "AP2127K-3_3TRG1")
)
