(part "MP2359DJ-LF-Z"
    (packageRef "SOT95P280X100-6N")
    (interface
        (port "1" (symbPinId 1) (portName "BST") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "FB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Monolithic Power Systems (MPS)")
    (property "Manufacturer_Part_Number" "MP2359DJ-LF-Z")
    (property "Mouser_Part_Number" "946-MP2359DJLFZ")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Monolithic-Power-Systems-MPS/MP2359DJ-LF-Z?qs=rC7bBWoQAAkgAaURxgQSyA%3D%3D")
    (property "Arrow_Part_Number" "MP2359DJ-LF-Z")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/mp2359dj-lf-z/monolithic-power-systems.html?utm_currency=USD&region=nac")
    (property "Description" "Voltage Regulators - Switching Regulators 1A 24V 1.4MHz Non-sync Buck")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/89d986a89c59d1844ef77b6f65b8a4d2.pdf")
    (property "symbolName1" "MP2359DJ-LF-Z")
)
