(part "bmp280"
    (packageRef "8-PIN-METAL-LID-LGA")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType GROUND))
        (port "2" (symbPinId 2) (portName "CSB") (portType INPUT))
        (port "3" (symbPinId 3) (portName "SDI") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCK") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VDDIO_1") (portType POWER))
        (port "7" (symbPinId 7) (portName "GND_2") (portType GROUND))
        (port "8" (symbPinId 8) (portName "VDDIO_2") (portType POWER))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "BOSCH")
    (property "Manufacturer_Part_Number" "bmp280")
    (property "Mouser_Part_Number" "262-BMP280")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bosch-Sensortec/BMP280?qs=QhAb4EtQfbUP9Z%252BCHM3Wyg%3D%3D")
    (property "Arrow_Part_Number" "BMP280")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bmp280/bosch?region=nac")
    (property "Description" "Digital Pressure Sensor")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/DKDS-24/462913.pdf")
    (property "symbolName1" "bmp280")
)
