(part "TPC8107"
    (packageRef "SOIC127P600X190-8N")
    (interface
        (port "1" (symbPinId 1) (portName "SOURCE_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SOURCE_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SOURCE_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GATE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "DRAIN_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "DRAIN_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DRAIN_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DRAIN_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Toshiba")
    (property "Manufacturer_Part_Number" "TPC8107")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "MOSFET MOSFET P-Ch 30V 13A Rdson=0.007Ohm")
    (property "Datasheet_Link" "https://datasheetspdf.com/pdf-file/312202/ToshibaSemiconductor/TPC8107/1")
    (property "symbolName1" "TPC8107")
)
