(part "FDMC8010"
    (packageRef "FDMC8010")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D_5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "FDMC8010")
    (property "Mouser_Part_Number" "512-FDMC8010")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/FDMC8010?qs=BiJXFBt7cx1GJPIblT9OBw%3D%3D")
    (property "Arrow_Part_Number" "FDMC8010")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/fdmc8010/on-semiconductor?region=nac")
    (property "Description" "Max RDS(on) = 1.3 m at VGS = 10 V, ID = 30 A; Max RDS(on) = 1.8 m at VGS = 4.5 V, ID = 25 A; High performance technology for extremely low RDS(on); Termination is Lead-free and RoHS Compliant")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/FDMC8010-D.PDF")
    (property "symbolName1" "FDMC8010")
)
